"""get DB blank state

Revision ID: 761c7f380258
Revises: 7666b4dd16fc
Create Date: 2025-01-24 11:14:13.188306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '761c7f380258'
down_revision = '7666b4dd16fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
